{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ec06a15e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9dfb8f4b8f0c46ecb68fbe5994eab302",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1000 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "402b2ae8e64c49599382cf9546b74a6d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/500 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "470ec61832fd4fa89eeca33588083c72",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/500 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "from data import generate_data\n",
    "from card_based import generate_genuine_data_small_amount, generate_genuine_data_huge_amount\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "import os\n",
    "import random\n",
    "import string\n",
    "from faker import   Faker\n",
    "import torch\n",
    "fake = Faker()\n",
    "from datetime import datetime\n",
    "from datetime import timedelta\n",
    "from tqdm.auto import tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19f3cba4",
   "metadata": {},
   "outputs": [],
   "source": [
    "generation_list = {\n",
    "    \"card_based\":\n",
    "    \"upi_wallet\": \n",
    "    \"netbanking\": \n",
    "    \"gift_atm\":\n",
    "    \"money_laundry\":\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 365,
   "id": "c313c6e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_category = { \"payment_method\": [\"Credit Card\", \"Debit Card\", \"Cash\", \"UPI\",\"Net Banking\"],\n",
    "    \"transaction_verification_method\": [\"PIN\", \"Signature\", \"Biometric\", \"OTP\", \"No Verification\"],\n",
    "    \"transaction_success\": [\"Purchase\", \"Transfer\", \"Payment\"],\n",
    "    \"transaction_failure\": [\"cancelled\",\"Network_failure\",\"authentication_error\"]}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 581,
   "id": "acffe650",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a736850c62b341bf9b2c264658f83972",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1000 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "def high_amount():\n",
    "    all_data= []\n",
    "    for i in tqdm(range(generate_data.GENERATE_COUNT)):\n",
    "        genuine = generate_genuine_data_small_amount(random.randint(1,4))\n",
    "        genuine[\"fake\"]=False\n",
    "        number = random.randint(1,2)\n",
    "        b = [(generate_data.generate_merchant_name(false_merchant = random.choice([True,False])), generate_data.generate_merchant_location(indian = random.choice([True,False])))  for i in range(number)]\n",
    "        l = []\n",
    "        if random.choice([True,False]):\n",
    "            d = generate_data.generate_multiple_date_sorted(number,start_date=genuine.trans_date.iloc[-1],end_date = \"now\")\n",
    "        else:\n",
    "            d =  generate_data.generate_multiple_date_sorted_small_precision(genuine.trans_date.iloc[-1], number)\n",
    "\n",
    "        for index,_ in enumerate(range(number)):\n",
    "            l.append((generate_data.generate_transaction_id_approval_code())+\n",
    "                      (genuine.customer_location.iloc[0],\n",
    "            generate_data.generate_transaction_category(), \n",
    "            generate_data.generate_transaction_currency(indian=random.choice([True,False])),\n",
    "            generate_data.generate_mcc(),\n",
    "            generate_data.generate_transaction_amount(small_amount=random.choice([True,False]),\n",
    "                                                  huge_amount=True,\n",
    "                                                  whole_number=random.choice([True,False])),\n",
    "            d[index],\n",
    "                    random.choice([\"Credit Card\", \"Debit Card\"]),\n",
    "                      random.choice([\"PIN\", \"Biometric\"]),\n",
    "                      random.choice([\"Purchase\", \"Transfer\", \"Payment\"])\n",
    "                )\n",
    "                    )\n",
    "        a = pd.concat([genuine[[\"cardholder_name\",\"card_number\",\"customer_age\",\"customer_segment\",\"card_type\",\"customer_location\"]].iloc[:1,:]]*number).reset_index(drop=True)\n",
    "        fake =  pd.concat([\n",
    "            a,\n",
    "                pd.DataFrame(b,columns=[\"merchant_name\",\"merchant_location\"]),\n",
    "                pd.DataFrame(l,columns=[\"trans_id\",\"trans_approval_code\",\"trans_loc\",\"trans_cat\",\n",
    "                                \"trans_currency\",\"mcc\",\"trans_amount\",\"trans_date\",\n",
    "                               \"trans_payment_method\",\"trans_verify_method\",\"trans_status\"])\n",
    "        ],axis=1)\n",
    "        fake[\"fake\"]=True\n",
    "        all_data.append(pd.concat([genuine,fake]))\n",
    "    return pd.concat(all_data)\n",
    "fake = high_amount()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 673,
   "id": "5a03e713",
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(\"/Users/amankumarpandey/Downloads/archive(2)/HI-Large_Patterns.txt\") as f:\n",
    "    data = f.readlines()\n",
    "new_data = []\n",
    "previous_index = 0\n",
    "for index,i in enumerate(data):\n",
    "    if i ==\"\\n\":\n",
    "        new_data.append(data[previous_index:index])\n",
    "        previous_index=index+1\n",
    "data = []\n",
    "for i in new_data:\n",
    "    value = i[0].split(\"-\")[-1].strip().split(\":\")[0]\n",
    "    data.extend([j[:-1]+\",\"+value+\"\\n\" for j  in i[1:-1]])\n",
    "a = \"Timestamp,From Bank,From Account,To Bank,To Account,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,Strategy\\n\"\n",
    "data.insert(0,a)\n",
    "data = \"\".join(data)\n",
    "df1 = pd.read_csv(StringIO(data))\n",
    "df = pd.read_csv(\"/Users/amankumarpandey/Downloads/archive(2)/HI-Large_Trans.csv\", nrows=10000)\n",
    "df1.to_csv(\"money_laundring.csv\",index=False)\n",
    "df[\"Strategy\"] = \"Nopeee\"\n",
    "df.columns = a.strip().split(\",\")\n",
    "df.to_csv(\"not_money_laundring.csv\",index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 674,
   "id": "4e19d584",
   "metadata": {},
   "outputs": [],
   "source": [
    "def money_laundring():\n",
    "    df = pd.read_csv(\"not_money_laundring.csv\")\n",
    "    df1 = pd.read_csv(\"money_laundring.csv\")\n",
    "    a = random.randint(1000,2000)\n",
    "    b = random.randint(3000,4000)\n",
    "    return pd.concat([df1.iloc[a:b],df.iloc[a:b]]) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 672,
   "id": "4e3d7a15",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Timestamp</th>\n",
       "      <th>From Bank</th>\n",
       "      <th>From Account</th>\n",
       "      <th>To Bank</th>\n",
       "      <th>To Account</th>\n",
       "      <th>Amount Received</th>\n",
       "      <th>Receiving Currency</th>\n",
       "      <th>Amount Paid</th>\n",
       "      <th>Payment Currency</th>\n",
       "      <th>Payment Format</th>\n",
       "      <th>Is Laundering</th>\n",
       "      <th>Strategy</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1136</th>\n",
       "      <td>2022/08/27 08:28</td>\n",
       "      <td>8285</td>\n",
       "      <td>80B47E730</td>\n",
       "      <td>25644</td>\n",
       "      <td>8078FCCF0</td>\n",
       "      <td>1847.01</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>1847.01</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>ACH</td>\n",
       "      <td>1</td>\n",
       "      <td>Out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1137</th>\n",
       "      <td>2022/08/28 17:16</td>\n",
       "      <td>8285</td>\n",
       "      <td>80B47E730</td>\n",
       "      <td>1924</td>\n",
       "      <td>8007E2C20</td>\n",
       "      <td>4348.95</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>4348.95</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>ACH</td>\n",
       "      <td>1</td>\n",
       "      <td>Out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1138</th>\n",
       "      <td>2022/08/01 17:04</td>\n",
       "      <td>2129461</td>\n",
       "      <td>83000DC90</td>\n",
       "      <td>239197</td>\n",
       "      <td>83000D0D0</td>\n",
       "      <td>34445.44</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>34445.44</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>ACH</td>\n",
       "      <td>1</td>\n",
       "      <td>In</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1139</th>\n",
       "      <td>2022/08/08 02:53</td>\n",
       "      <td>29</td>\n",
       "      <td>82E2CB5B0</td>\n",
       "      <td>239197</td>\n",
       "      <td>83000D0D0</td>\n",
       "      <td>61575.71</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>61575.71</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>ACH</td>\n",
       "      <td>1</td>\n",
       "      <td>In</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1140</th>\n",
       "      <td>2022/08/08 19:11</td>\n",
       "      <td>2126306</td>\n",
       "      <td>83000CE40</td>\n",
       "      <td>239197</td>\n",
       "      <td>83000D0D0</td>\n",
       "      <td>61070.66</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>61070.66</td>\n",
       "      <td>Yuan</td>\n",
       "      <td>ACH</td>\n",
       "      <td>1</td>\n",
       "      <td>In</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3483</th>\n",
       "      <td>2022/08/01 00:25</td>\n",
       "      <td>31007</td>\n",
       "      <td>8005E6EE0</td>\n",
       "      <td>31007</td>\n",
       "      <td>8005E6EE0</td>\n",
       "      <td>23692.39</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>23692.39</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>Reinvestment</td>\n",
       "      <td>0</td>\n",
       "      <td>Nopeee</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3484</th>\n",
       "      <td>2022/08/01 00:03</td>\n",
       "      <td>3725</td>\n",
       "      <td>8005E7560</td>\n",
       "      <td>2597</td>\n",
       "      <td>800387420</td>\n",
       "      <td>114.51</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>114.51</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>ACH</td>\n",
       "      <td>0</td>\n",
       "      <td>Nopeee</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3485</th>\n",
       "      <td>2022/08/01 00:12</td>\n",
       "      <td>741</td>\n",
       "      <td>8005F0180</td>\n",
       "      <td>741</td>\n",
       "      <td>8005F0180</td>\n",
       "      <td>20956.12</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>20956.12</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>Reinvestment</td>\n",
       "      <td>0</td>\n",
       "      <td>Nopeee</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3486</th>\n",
       "      <td>2022/08/01 00:13</td>\n",
       "      <td>20</td>\n",
       "      <td>800398080</td>\n",
       "      <td>1818</td>\n",
       "      <td>8005F01D0</td>\n",
       "      <td>105266.47</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>105266.47</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>ACH</td>\n",
       "      <td>0</td>\n",
       "      <td>Nopeee</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3487</th>\n",
       "      <td>2022/08/01 00:12</td>\n",
       "      <td>952</td>\n",
       "      <td>8006719E0</td>\n",
       "      <td>952</td>\n",
       "      <td>8006719E0</td>\n",
       "      <td>62388.04</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>62388.04</td>\n",
       "      <td>US Dollar</td>\n",
       "      <td>Reinvestment</td>\n",
       "      <td>0</td>\n",
       "      <td>Nopeee</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4704 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             Timestamp  From Bank From Account  To Bank To Account  \\\n",
       "1136  2022/08/27 08:28       8285    80B47E730    25644  8078FCCF0   \n",
       "1137  2022/08/28 17:16       8285    80B47E730     1924  8007E2C20   \n",
       "1138  2022/08/01 17:04    2129461    83000DC90   239197  83000D0D0   \n",
       "1139  2022/08/08 02:53         29    82E2CB5B0   239197  83000D0D0   \n",
       "1140  2022/08/08 19:11    2126306    83000CE40   239197  83000D0D0   \n",
       "...                ...        ...          ...      ...        ...   \n",
       "3483  2022/08/01 00:25      31007    8005E6EE0    31007  8005E6EE0   \n",
       "3484  2022/08/01 00:03       3725    8005E7560     2597  800387420   \n",
       "3485  2022/08/01 00:12        741    8005F0180      741  8005F0180   \n",
       "3486  2022/08/01 00:13         20    800398080     1818  8005F01D0   \n",
       "3487  2022/08/01 00:12        952    8006719E0      952  8006719E0   \n",
       "\n",
       "      Amount Received Receiving Currency  Amount Paid Payment Currency  \\\n",
       "1136          1847.01          US Dollar      1847.01        US Dollar   \n",
       "1137          4348.95          US Dollar      4348.95        US Dollar   \n",
       "1138         34445.44               Yuan     34445.44             Yuan   \n",
       "1139         61575.71               Yuan     61575.71             Yuan   \n",
       "1140         61070.66               Yuan     61070.66             Yuan   \n",
       "...               ...                ...          ...              ...   \n",
       "3483         23692.39          US Dollar     23692.39        US Dollar   \n",
       "3484           114.51          US Dollar       114.51        US Dollar   \n",
       "3485         20956.12          US Dollar     20956.12        US Dollar   \n",
       "3486        105266.47          US Dollar    105266.47        US Dollar   \n",
       "3487         62388.04          US Dollar     62388.04        US Dollar   \n",
       "\n",
       "     Payment Format  Is Laundering Strategy  \n",
       "1136            ACH              1      Out  \n",
       "1137            ACH              1      Out  \n",
       "1138            ACH              1       In  \n",
       "1139            ACH              1       In  \n",
       "1140            ACH              1       In  \n",
       "...             ...            ...      ...  \n",
       "3483   Reinvestment              0   Nopeee  \n",
       "3484            ACH              0   Nopeee  \n",
       "3485   Reinvestment              0   Nopeee  \n",
       "3486            ACH              0   Nopeee  \n",
       "3487   Reinvestment              0   Nopeee  \n",
       "\n",
       "[4704 rows x 12 columns]"
      ]
     },
     "execution_count": 672,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "money_laundring()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "f8e8ee8b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pydantic in /opt/homebrew/lib/python3.11/site-packages (1.10.12)\n",
      "Collecting pydantic\n",
      "  Obtaining dependency information for pydantic from https://files.pythonhosted.org/packages/82/06/fafdc75e48b248eff364b4249af4bcc6952225e8f20e8205820afc66e88e/pydantic-2.3.0-py3-none-any.whl.metadata\n",
      "  Using cached pydantic-2.3.0-py3-none-any.whl.metadata (148 kB)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic) (0.5.0)\n",
      "Collecting pydantic-core==2.6.3 (from pydantic)\n",
      "  Obtaining dependency information for pydantic-core==2.6.3 from https://files.pythonhosted.org/packages/c4/dc/bbc346df4afa3aa4c9ec2a6d22c9fd31c326a2d99a491055d735519c2a3f/pydantic_core-2.6.3-cp311-cp311-macosx_11_0_arm64.whl.metadata\n",
      "  Using cached pydantic_core-2.6.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.5 kB)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in /opt/homebrew/lib/python3.11/site-packages (from pydantic) (4.7.1)\n",
      "Using cached pydantic-2.3.0-py3-none-any.whl (374 kB)\n",
      "Using cached pydantic_core-2.6.3-cp311-cp311-macosx_11_0_arm64.whl (1.6 MB)\n",
      "Installing collected packages: pydantic-core, pydantic\n",
      "  Attempting uninstall: pydantic\n",
      "    Found existing installation: pydantic 1.10.12\n",
      "    Uninstalling pydantic-1.10.12:\n",
      "      Successfully uninstalled pydantic-1.10.12\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.7.5 which is incompatible.\n",
      "ydata-profiling 4.5.1 requires pydantic<2,>=1.8.1, but you have pydantic 2.3.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed pydantic-2.3.0 pydantic-core-2.6.3\n"
     ]
    }
   ],
   "source": [
    "# df = pd.read_csv(\"local_data/big_amount_deduction.csv\")\n",
    "!pip install -U pydantic"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "924a47be",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pydantic._migration failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_migration.py\", line 6, in <module>\n",
      "    from .version import version_short\n",
      "ImportError: cannot import name 'version_short' from 'pydantic.version' (/opt/homebrew/lib/python3.11/site-packages/pydantic/version.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.warnings failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/warnings.py\", line 4, in <module>\n",
      "    from .version import version_short\n",
      "ImportError: cannot import name 'version_short' from 'pydantic.version' (/opt/homebrew/lib/python3.11/site-packages/pydantic/version.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.deprecated.config failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 496, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 393, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 361, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 319, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to _ConfigMetaclass object\n",
      "]\n",
      "[autoreload of pydantic._internal._config failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_config.py\", line 9, in <module>\n",
      "    from ..config import ConfigDict, ExtraValues, JsonEncoder, JsonSchemaExtraCallable\n",
      "ImportError: cannot import name 'ConfigDict' from 'pydantic.config' (/opt/homebrew/lib/python3.11/site-packages/pydantic/config.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._mock_val_ser failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py\", line 8, in <module>\n",
      "    from ..errors import PydanticErrorCodes, PydanticUserError\n",
      "ImportError: cannot import name 'PydanticErrorCodes' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.json_schema failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/json_schema.py\", line 45, in <module>\n",
      "    from .config import JsonSchemaExtraCallable\n",
      "ImportError: cannot import name 'JsonSchemaExtraCallable' from 'pydantic.config' (/opt/homebrew/lib/python3.11/site-packages/pydantic/config.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._decorators failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_decorators.py\", line 14, in <module>\n",
      "    from ..errors import PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUserError' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._discriminated_union failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_discriminated_union.py\", line 7, in <module>\n",
      "    from ..errors import PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUserError' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._generate_schema failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py\", line 40, in <module>\n",
      "    from ..config import ConfigDict, JsonEncoder\n",
      "ImportError: cannot import name 'ConfigDict' from 'pydantic.config' (/opt/homebrew/lib/python3.11/site-packages/pydantic/config.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._dataclasses failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py\", line 15, in <module>\n",
      "    from ..errors import PydanticUndefinedAnnotation\n",
      "ImportError: cannot import name 'PydanticUndefinedAnnotation' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._decorators_v1 failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_decorators_v1.py\", line 10, in <module>\n",
      "    from ..errors import PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUserError' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.deprecated.class_validators failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py\", line 13, in <module>\n",
      "    from ..errors import PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUserError' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._validate_call failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py\", line 10, in <module>\n",
      "    from ..config import ConfigDict\n",
      "ImportError: cannot import name 'ConfigDict' from 'pydantic.config' (/opt/homebrew/lib/python3.11/site-packages/pydantic/config.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic._internal._model_construction failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 15, in <module>\n",
      "    from ..errors import PydanticUndefinedAnnotation, PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUndefinedAnnotation' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.type_adapter failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/type_adapter.py\", line 11, in <module>\n",
      "    from pydantic.errors import PydanticUserError\n",
      "ImportError: cannot import name 'PydanticUserError' from 'pydantic.errors' (/opt/homebrew/lib/python3.11/site-packages/pydantic/errors.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.functional_serializers failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/functional_serializers.py\", line 12, in <module>\n",
      "    from . import PydanticUndefinedAnnotation\n",
      "ImportError: cannot import name 'PydanticUndefinedAnnotation' from 'pydantic' (/opt/homebrew/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)\n",
      "]\n",
      "[autoreload of pydantic.functional_validators failed: Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 273, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/extensions/autoreload.py\", line 471, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pydantic/functional_validators.py\", line 15, in <module>\n",
      "    from . import GetCoreSchemaHandler as _GetCoreSchemaHandler\n",
      "ImportError: cannot import name 'GetCoreSchemaHandler' from 'pydantic' (/opt/homebrew/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)\n",
      "]\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'BaseModel' from 'pydantic' (/opt/homebrew/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[30], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ProfileReport\u001b[38;5;66;03m#defining the library\u001b[39;00m\n\u001b[1;32m      2\u001b[0m profile \u001b[38;5;241m=\u001b[39m ProfileReport(df)\u001b[38;5;66;03m# exporting your report as a html file\u001b[39;00m\n\u001b[1;32m      3\u001b[0m profile\u001b[38;5;241m.\u001b[39mto_file(output_file\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mreport.html\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m/opt/homebrew/lib/python3.11/site-packages/ydata_profiling/__init__.py:7\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;124;03m\"\"\"Main module of ydata-profiling.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \n\u001b[1;32m      3\u001b[0m \u001b[38;5;124;03m.. include:: ../../README.md\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mimportlib\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutil\u001b[39;00m\n\u001b[0;32m----> 7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcompare_reports\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m compare\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcontroller\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m pandas_decorator\n\u001b[1;32m      9\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mprofile_report\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ProfileReport\n",
      "File \u001b[0;32m/opt/homebrew/lib/python3.11/site-packages/ydata_profiling/compare_reports.py:9\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdacite\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m from_dict\n\u001b[0;32m----> 9\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mconfig\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Correlation, Settings\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodel\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BaseDescription\n\u001b[1;32m     11\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mydata_profiling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodel\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01malerts\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Alert\n",
      "File \u001b[0;32m/opt/homebrew/lib/python3.11/site-packages/ydata_profiling/config.py:7\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtyping\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Any, Dict, List, Optional, Tuple, Union\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01myaml\u001b[39;00m\n\u001b[0;32m----> 7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpydantic\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BaseModel, BaseSettings, Field, PrivateAttr\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_merge_dictionaries\u001b[39m(dict1: \u001b[38;5;28mdict\u001b[39m, dict2: \u001b[38;5;28mdict\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mdict\u001b[39m:\n\u001b[1;32m     11\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;124;03m    Recursive merge dictionaries.\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     16\u001b[0m \u001b[38;5;124;03m    :return: Merged dictionary\u001b[39;00m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'BaseModel' from 'pydantic' (/opt/homebrew/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)"
     ]
    }
   ],
   "source": [
    "\n",
    "from ydata_profiling import ProfileReport#defining the library\n",
    "profile = ProfileReport(df)# exporting your report as a html file\n",
    "profile.to_file(output_file='report.html')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06d6639c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
